src/AppBundle/Entity/ForumBan.php
<?php

namespace Raddit\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;

/**
 * Represents a ban or unban action that applies to a user and a forum.
 *
 * @ORM\Entity(repositoryClass="Raddit\AppBundle\Repository\ForumBanRepository")
 * @ORM\Table(name="forum_bans")
 */
class ForumBan {
    /**
     * @ORM\Column(type="uuid")
     * @ORM\Id()
     *
     * @var Uuid
     */
    private $id;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="Forum", inversedBy="bans")
     *
     * @var Forum
     */
    private $forum;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $user;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $reason;

    /**
     * @ORM\Column(type="boolean")
     *
     * @var bool
     */
    private $banned;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $bannedBy;

    /**
     * @ORM\Column(type="datetimetz")
     *
     * @var \DateTime
     */
    private $timestamp;

    /**
     * @ORM\Column(type="datetimetz", nullable=true)
     */
    private $expiresAt;

    public function __construct(
        Forum $forum,
        User $user,
        string $reason,
        bool $banned,
        User $bannedBy,
        \DateTime $expiresAt = null,
        \DateTime $timestamp = null
    ) {
        if (!$banned && $expiresAt) {
            throw new \DomainException('Unbans cannot have expiry times');
        }

        $this->id = Uuid::uuid4();
        $this->forum = $forum;
        $this->user = $user;
        $this->reason = $reason;
        $this->banned = $banned;
        $this->bannedBy = $bannedBy;
        $this->expiresAt = $expiresAt;

        // since the last ban takes precedence, and because timestamps are used
        // for sorting, we'll use microseconds to hopefully avoid collisions
        $this->timestamp = $timestamp ?:
            \DateTime::createFromFormat('U.u', microtime(true));
    }

    public function getId(): Uuid {
        return $this->id;
    }

    public function getForum(): Forum {
        return $this->forum;
    }

    public function getUser(): User {
        return $this->user;
    }

    public function getReason(): string {
        return $this->reason;
    }

    public function isBan(): bool {
        return $this->banned;
    }

    public function getTimestamp(): \DateTime {
        return $this->timestamp;
    }

    /**
     * @return \DateTime|null
     */
    public function getExpiryTime() {
        return $this->expiresAt;
    }
}

src/AppBundle/Resources/views/add_moderator.html.twig
{% extends '@RadditApp/forum_base.html.twig' %}

{% block page_classes %}
  add-moderators-page
{% endblock %}

{% block title %}
  {{ 'add_moderator.title'|trans({'%forum%': forum.name}) }}
{% endblock %}

{% block body %}
  <h1>{{ block('title') }}</h1>

  {{ form(form) }}
{% endblock %}

src/AppBundle/Resources/views/all.html.twig
{% extends '@RadditApp/front.html.twig' %}

{% block page_classes %}
  all-page
{% endblock %}

{% block sidebar %}{% endblock %}

src/AppBundle/Resources/views/base.html.twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}" prefix="og: http://ogp.me/ns#">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %}{{ raddit_app_site_name() }}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="generator" content="raddit {{ raddit_app_version() }}">

    <link rel="apple-touch-icon-precomposed" href="{{ asset('apple-touch-icon-precomposed.png') }}">

    {% block stylesheets %}
      {{ include('@RadditApp/includes/stylesheets.html.twig', {
        theme: app.user.preferredTheme ?? null,
        night_mode: app.user.nightMode ?? false,
      }) }}
    {% endblock %}

    {% block head %}{% endblock %}
  </head>

  <body class="{{ block('page_classes')|replace({'\n': ''}) }} {{ app.user ? 'user-logged-in' : 'user-anonymous' }}">
    {% include '@RadditApp/includes/site_nav.html.twig' %}

    <div class="site-alerts">
      {%- for type, notices in app.flashes -%}
        {%- for notice in notices -%}
          <div class="alert alert--{{ type }} alert--animate alert--dismissable" role="alert">
            <p>{{ notice|trans }}</p>
          </div>
        {%- endfor -%}
      {%- endfor -%}
    </div>

    <div class="content-wrapper">
      <main class="body">{% block body %}{% endblock %}</main>
      <aside class="sidebar">{% block sidebar %}{% endblock %}</aside>
    </div>

    <footer class="site-footer">
      <p class="site-footer-version">
        {{ 'site_footer.version'|trans({
          '%branch%': raddit_app_branch(),
          '%version%': raddit_app_version(),
          '%app%': '<a href="https://gitlab.com/edgyemma/raddit-app">raddit</a>',
        })|raw }}
      </p>
    </footer>

    {% block javascripts %}
      <script src="{{ preload(asset('bundles/fosjsrouting/js/router.js')) }}"></script>
      <script src="{{ path('fos_js_routing_js', {callback: 'fos.Router.setData'}) }}"></script>
      <script src="{{ preload(asset('build/manifest.js')) }}"></script>
      <script src="{{ preload(asset('build/vendor.js')) }}"></script>
      <script src="{{ preload(asset('build/main.js')) }}"></script>
      <script src="{{ path('bazinga_jstranslation_js') }}"></script>
    {% endblock %}
  </body>
</html>

src/AppBundle/Resources/views/featured.xml.twig
<?xml version="1.0" encoding="utf-8" ?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>{{ raddit_app_site_name() }}</title>
  <subtitle>{{ 'title.submissions_in_featured_forums'|trans }}</subtitle>
  <updated>{{ 'now'|date('c') }}</updated>

  {% with { route: app.request.attributes.get('_route'), params: app.request.attributes.get('_route_params') } %}
    <id>{{ url(route, params) }}</id>

    <link rel="self" href="{{ url(route, params) }}" />
    {% if submissions.hasNextPage %}
      <link rel="next" href="{{ url(route, params|merge({page: submissions.nextPage})) }}"/>
    {% endif %}
    {% if submissions.hasPreviousPage %}
      <link rel="previous" href="{{ url(route, params|merge({page: submissions.nextPage})) }}"/>
    {% endif %}
  {% endwith %}

  {% for submission in submissions %}
    {% set uri = url('raddit_app_comments', {forum_name: submission.forum.name, submission_id: submission.id}) %}
    <entry>
      <id>{{ uri }}</id>
      <link href="{{ uri }}" />
      <title>{{ submission.title }}</title>
      <published>{{ submission.timestamp|date('c') }}</published>
      <updated>{{ (submission.editedAt ?? submission.timestamp)|date('c') }}</updated>
      <author>
        <name>{{ submission.user.username }}</name>
        <uri>{{ url('raddit_app_user', {username: submission.user.username}) }}</uri>
      </author>
      <category term="{{ submission.forum.name }}" label="{{ submission.forum.title }}" scheme="{{ app.request.getUriForPath('/f/') }}"/>
      <content type="html">
        {%- if submission.body is not null -%}
          <![CDATA[{{ submission.body|cached_markdown|raw }}]]>
        {%- endif -%}
      </content>
    </entry>
  {% endfor %}
</feed>

src/AppBundle/Resources/views/forum_appearance.html.twig
{% extends '@RadditApp/forum_base.html.twig' %}

{% block title 'title.forum_appearance'|trans({'%forum%': '/f/%s'|format(forum.name)}) %}
{% block page_classes 'forum-appearance-page' %}

{% block body %}
  <h1>
    {{ 'title.forum_appearance'|trans({'%forum%': '<a href="%s">/f/%s</a>'|format(
      path('raddit_app_forum', {forum_name: forum.name})|escape,
      forum.name|escape
    )})|raw }}
  </h1>

  {{ form_start(form) }}
    {{ form_row(form.theme, {attr: {class: 'select2'}}) }}

    {# todo: some navigation widget thing #}
    <nav>
      <ul>
        <li><a href="{{ path('raddit_app_themes') }}">{{ 'nav.themes'|trans }}</a></li>
        <li><a href="{{ path('raddit_app_create_theme') }}">{{ 'nav.create_theme'|trans }}</a></li>
      </ul>
    </nav>
  {{ form_end(form) }}
{% endblock %}

src/AppBundle/Resources/views/forum_ban.html.twig
{% extends '@RadditApp/forum_base.html.twig' %}

{% block page_classes 'forum-ban-page' %}
{% block title 'title.banning_user_from_forum'|trans({
  '%forum%': forum.name,
  '%user%': user.username,
}) %}

{% block body %}
  <h1>{{ block('title') }}</h1>

  {{ form(form) }}
{% endblock %}

src/AppBundle/Resources/views/forum_bans.html.twig
{% extends '@RadditApp/forum_base.html.twig' %}
{% from '@RadditApp/macros/user_macros.html.twig' import user_link %}

{% block page_classes 'forum-bans-page' %}
{% block title 'title.bans_in_forum'|trans({'%forum%': '/f/'~forum.name}) %}

{% block head %}
  {{ include('@RadditApp/includes/meta_pagination.html.twig', {pager: bans}, with_context=false) }}
{% endblock %}

{% block body %}
  <h1>{{ block('title') }}</h1>

  <table class="table">
    <thead>
    <tr>
      <th>{{ 'label.username'|trans }}</th>
      <th>{{ 'label.reason'|trans }}</th>
      <th>{{ 'label.banned'|trans }}</th>
      <th>{{ 'label.expires'|trans }}</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
      {% for ban in bans %}
        <tr>
          <td>
            {{ user_link(ban.user) }}
          </td>
          <td>{{ ban.reason }}</td>
          <td>
            {% with {date: ban.timestamp|localizeddate('long', 'short')} %}
              <time datetime="{{ ban.timestamp|date('c') }}" class="relative-time" title="{{ date }}">
                {{- date -}}
              </time>
            {% endwith %}
          </td>
          <td>
            {% if ban.expiryTime %}
              {% with {date: ban.expiryTime|localizeddate('long', 'short')} %}
                <time datetime="{{ ban.expiryTime|date('c') }}" class="relative-time" title="{{ date }}">
                  {{- date -}}
                </time>
              {% endwith %}
            {% else %}
              {{ 'label.never'|trans }}
            {% endif %}
          </td>
          <td>
            <a href="{{ path('raddit_app_forum_ban_history', {forum_name: forum.name, username: ban.user.username}) }}"
               class="button button--inline">
              {{- 'nav.ban_history'|trans -}}
            </a>
            <a href="{{ path('raddit_app_forum_unban', {forum_name: forum.name, username: ban.user.username}) }}"
               class="button button--inline">
              {{- 'action.unban'|trans -}}
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {{ include('@RadditApp/includes/pagination.html.twig', {pager: bans}, with_context=false) }}
{% endblock %}

src/AppBundle/Resources/views/forum_base.html.twig
{% extends '@RadditApp/base.html.twig' %}

{% block stylesheets %}
  {% if app.user.showCustomStylesheets ?? false and forum.theme %}
    {{ include('@RadditApp/includes/stylesheets.html.twig', {
      theme: forum.theme,
      night_mode: app.user.nightMode ?? false
    }, with_context=false) }}
  {% else %}
    {{ parent() }}
  {% endif %}
{% endblock %}

{% block sidebar %}
    <section class="sidebar__section sidebar__section--forum-meta forum-meta">
      <h1 class="sidebar__title forum-title"><a href="{{ path('raddit_app_forum', {forum_name: forum.name}) }}">{{ forum.title }}</a></h1>

      {% if is_granted('ROLE_USER') %}
        {% from '@RadditApp/macros/forum_macros.html.twig' import subscribe_button %}
        {% set subscribed = forum.subscribed(app.user) %}
        <form action="{{ path(subscribed ? 'raddit_app_unsubscribe' : 'raddit_app_subscribe', {id: forum.id}) }}" method="POST" class="form">
          <input type="hidden" name="token" value="{{ csrf_token('subscribe') }}">

          <div class="form__row">
            {{ subscribe_button(forum, subscribed, false) }}
          </div>
        </form>
      {% endif %}

      {% if forum.sidebar is not empty %}
        <div class="forum-sidebar-content">{{ forum.sidebar|cached_markdown|raw }}</div>
      {% endif %}
    </section>

    {% if is_granted('moderator', forum) %}
      <section class="sidebar__section sidebar__section--forum-manage forum-manage">
        <h1 class="sidebar__title">{{ 'forum.manage'|trans }}</h1>
        <ul>
          <li><a href="{{ path('raddit_app_edit_forum', {forum_name: forum.name}) }}">{{ 'forum.edit'|trans }}</a></li>
          <li><a href="{{ path('raddit_app_forum_appearance', {forum_name: forum.name}) }}">{{ 'nav.appearance'|trans }}</a></li>
          {% if is_granted('moderator', forum) %}
            <li><a href="{{ path('raddit_app_forum_bans', {forum_name: forum.name}) }}">{{ 'nav.bans'|trans }}</a></li>
          {% endif %}
          {% if is_granted('ROLE_ADMIN') %}
            <li><a href="{{ path('raddit_app_add_moderator', {forum_name: forum.name}) }}">{{ 'forum.add_moderator'|trans }}</a></li>
            <li><a href="{{ path('raddit_app_delete_forum', {forum_name: forum.name}) }}">{{ 'nav.delete_forum'|trans }}</a></li>
          {% endif %}
        </ul>
      </section>
    {% endif %}

    {% if forum.moderators|length > 0 %}
      <section class="sidebar__section sidebar__section--forum-moderators forum-moderators">
        <h1 class="sidebar__title"><a href="{{ path('raddit_app_forum_moderators', {forum_name: forum.name}) }}">{{ 'forum.moderators'|trans }}</a></h1>
        <ul>
          {% for moderator in forum.moderators %}
            <li>
              <a href="{{ path('raddit_app_user', {username: moderator.user.username}) }}">
                {{- moderator.user.username -}}
              </a>
            </li>
          {% endfor %}
        </ul>
      </section>
    {% endif %}
{% endblock %}

src/AppBundle/Resources/views/forum_list.html.twig
{% extends '@RadditApp/base.html.twig' %}
{% from '@RadditApp/forums_by_category.html.twig' import forum_view_selector %}

{% block page_classes %}
  forum-list-page
{% endblock %}

{% block title %}
  {{- 'forum_list.page_title'|trans -}}
{% endblock %}

{% block head %}
  <link rel="canonical" href="{{ url('raddit_app_forum_list') }}">
  {% include '@RadditApp/includes/meta_pagination.html.twig' with {pager: forums} %}
{% endblock %}

{% from _self import table_head as th %}
{% from '@RadditApp/macros/forum_list_macros.html.twig' import forum_list_header %}

{% block body %}
  {{ forum_list_header() }}

  <table class="table table--fixed-columns forum-list">
    <thead>
      <tr>
        <th>{{ th('forum_list.name'|trans, 'by_name', sortBy) }}</th>
        <th>{{ th('forum_list.title'|trans, 'by_title', sortBy) }}</th>
        <th>{{ th('forum_list.submission_count'|trans, 'by_submissions', sortBy) }}</th>
        <th>{{ th('forum_list.subscribers'|trans, 'by_subscribers', sortBy) }}</th>
      </tr>
    </thead>
    <tbody>
      {% for forum in forums %}
        <tr>
          <td><a href="{{ path('raddit_app_forum', {forum_name: forum.name}) }}"><strong>{{ forum.name }}</strong></a></td>
          <td>{{ forum.title }}</td>
          <td>{{ forum.submissions|length|localizednumber }}</td>
          {% if is_granted('ROLE_USER') %}
            {% from '@RadditApp/macros/forum_macros.html.twig' import subscribe_button %}
            {% set subscribed = forum.subscribed(app.user) %}
            <td>
              <form action="{{ path(subscribed ? 'raddit_app_unsubscribe' : 'raddit_app_subscribe', {id: forum.id}) }}" method="POST">
                <input type="hidden" name="token" value="{{ csrf_token('subscribe') }}">
                {{ subscribe_button(forum, subscribed, true) }}
              </form>
            </td>
          {% else %}
            <td>{{ forum.subscriptions|length|localizednumber }}</td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% include '@RadditApp/includes/pagination.html.twig' with {pager: forums} %}
{% endblock %}

{% macro table_head(label, newSortBy, currentSortBy) %}
  {%- if newSortBy == currentSortBy -%}
    {{ label }} &#x25BC;
  {% else %}
    <a href="{{ path('raddit_app_forum_list', app.request.attributes.get('_route_params')|merge({sortBy: newSortBy})) }}">
      {{- label -}}
    </a>
  {%- endif -%}
{% endmacro %}

src/AppBundle/Resources/views/forum_moderators.html.twig
{% extends '@RadditApp/forum_base.html.twig' %}

{% block page_classes %}
  forum-moderators-page
{% endblock %}

{% block title %}
  {{ 'forum_moderators.title'|trans({'%forum_name%': forum.name}) }}
{% endblock %}

{% block head %}
  {{ include('@RadditApp/includes/meta_pagination.html.twig', {pager: moderators}, with_context=false) }}
{% endblock %}

{% block body %}
  <h1>{{ block('title') }}</h1>

  <table class="table">
    <thead>
      <tr>
        <th>{{ 'forum_moderators.username'|trans }}</th>
        <th>{{ 'forum_moderators.since'|trans }}</th>
        <th>{{ 'forum_moderators.last_seen'|trans }}</th>
      </tr>
    </thead>
    <tbody>
      {% for moderator in moderators %}
      <tr>
        <td><a href="{{ path('raddit_app_user', {username: moderator.user.username}) }}">{{ moderator.user.username }}</a></td>
        <td>
          <time datetime="{{ moderator.timestamp|date('c') }}" title="{{ moderator.timestamp|localizeddate('long', 'short') }}" class="relative-time">
            {{ moderator.timestamp|localizeddate('long', 'short') }}
          </time>
        </td>
        <td>
          {% if moderator.user.lastSeen is not null %}
          <time datetime="{{ moderator.user.lastSeen|date('c') }}" title="{{ moderator.user.lastSeen|localizeddate('long', 'short') }}" class="relative-time">
            {{ moderator.user.lastSeen|localizeddate('long', 'short') }}
          </time>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {{ include('@RadditApp/includes/pagination.html.twig', {pager: moderators}, with_context=false) }}
{% endblock %}

src/AppBundle/Resources/views/forum_unban.html.twig
{% extends '@RadditApp/forum_ban.html.twig' %}

{% block title 'title.unbanning_user_from_forum'|trans({
  '%user%': '/u/'~user.username,
  '%forum%': '/f/'~forum.name,
}) %}

{% block page_classes 'forum-unban-page' %}

src/AppBundle/Resources/views/message.html.twig
{% extends '@RadditApp/base.html.twig' %}
{% from '@RadditApp/macros/messages.html.twig' import message_thread %}

{% block page_classes %}
  message-page
{% endblock %}

{% block title %}
  {{ thread.title }}
{% endblock %}

{% block body %}
  <h1>{{ thread.title }}</h1>

  {{ message_thread(thread) }}

  {{ form_start(form) }}
    {{ form_row(form.body, {attr: {rows: 6}}) }}

    {{ form_row(form.submit) }}
  {{ form_end(form) }}
{% endblock %}

src/AppBundle/Resources/views/message_list.html.twig
{% extends '@RadditApp/base.html.twig' %}

{% block page_classes %}
  message-list-page
{% endblock %}

{% block head %}
  {% include '@RadditApp/includes/meta_pagination.html.twig' with {pager: messages} %}
{% endblock %}

{% block title %}
  {{ 'message_list.page_title'|trans }}
{% endblock %}

{% block body %}
  <h1>{{ block('title') }}</h1>

  {% if messages|length > 0 %}
    <table class="table">
      <thead>
      <tr>
        <th>{{ 'message_list.title'|trans }}</th>
        <th>{{ 'message_list.sent'|trans }}</th>
        <th>{{ 'message_list.replies'|trans }}</th>
        <th>{{ 'message_list.from'|trans }}</th>
        <th>{{ 'message_list.to'|trans }}</th>
      </tr>
      </thead>
      <tbody>
      {% for message in messages %}
        <tr>
          <td><strong><a href="{{ path('raddit_app_message', {id: message.id}) }}">{{ message.title }}</a></strong></td>
          <td>
            <time class="relative-time" datetime="{{ message.timestamp|date('c') }}">
              {{ message.timestamp|localizeddate('long', 'short') }}
            </time>
          </td>
          <td>{{ message.replies|length|localizednumber }}</td>
          <td><a href="{{ path('raddit_app_user', {username: message.sender.username}) }}">{{ message.sender.username }}</a></td>
          <td><a href="{{ path('raddit_app_user', {username: message.receiver.username}) }}">{{ message.receiver.username }}</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>{{ 'message_list.no_messages'|trans }}</p>
  {% endif %}

  {% include '@RadditApp/includes/pagination.html.twig' with {pager: messages} %}
{% endblock %}

src/AppBundle/Resources/views/wiki_revision.html.twig
{% extends '@RadditApp/wiki.html.twig' %}

{% block title %}
  {{ 'title.showing_revision'|trans({
    '%revision%': revision.id|localizednumber,
    '%path%': '<a href="%s">%s</a>'|format(path('raddit_app_wiki', {path: page.path})|e, page.path|e),
  })|raw }}
{% endblock %}

{% block page_classes 'wiki-revision-page' %}

{% block body %}
  <h1>{{ block('title') }}</h1>
  <hr>

  <article>
    <h1>{{ revision.title }}</h1>

    {{ revision.body|cached_markdown|raw }}
  </article>
  <hr>

  <form class="form">
    <div class="form__row">
      <label class="form__label" for="revision-source">{{ 'label.source_code'|trans }}</label>
      <textarea rows="12" id="revision-source" readonly>{{ revision.body }}</textarea>
    </div>
  </form>
{% endblock %}