src/AppBundle/Entity/Votable.php
<?php

namespace Raddit\AppBundle\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Collections\Selectable;

abstract class Votable {
    // these values should probably never change
    const USER_NO_VOTE = 0;
    const USER_UPVOTED = 1;
    const USER_DOWNVOTED = -1;

    const VOTE_UP = 1;
    const VOTE_DOWN = -1;
    const VOTE_RETRACT = 0;
    const VOTE_CHOICES = [self::VOTE_UP, self::VOTE_DOWN, self::VOTE_RETRACT];

    /**
     * @param Votable $a
     * @param Votable $b
     *
     * @return int
     */
    final public static function descendingNetScoreCmp(self $a, self $b) {
        return $b->getNetScore() <=> $a->getNetScore();
    }

    /**
     * @return Vote[]|Collection|Selectable
     */
    abstract public function getVotes();

    /**
     * @param User        $user
     * @param string|null $ip
     * @param int         $choice
     *
     * @return Vote
     */
    abstract protected function createVote(User $user, $ip, int $choice): Vote;

    /**
     * @param User        $user
     * @param string|null $ip
     * @param int         $choice
     *
     * @throws \InvalidArgumentException if the vote is not a VOTE_* constant
     */
    public function vote(User $user, $ip, int $choice) {
        $vote = $this->getUserVote($user);

        if ($choice === self::VOTE_UP || $choice === self::VOTE_DOWN) {
            if ($vote) {
                $vote->setChoice($choice);
            } else {
                $this->getVotes()->add($this->createVote($user, $ip, $choice));
            }
        } elseif ($choice === self::VOTE_RETRACT) {
            $this->getVotes()->removeElement($vote);
        } else {
            throw new \InvalidArgumentException('Bad vote choice');
        }
    }

    /**
     * @return int
     */
    public function getUpvotes(): int {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('upvote', true));

        return count($this->getVotes()->matching($criteria));
    }

    public function getDownvotes(): int {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('upvote', false));

        return count($this->getVotes()->matching($criteria));
    }

    public function getNetScore(): int {
        return $this->getUpvotes() - $this->getDownvotes();
    }

    public function getUserChoice(User $user): int {
        $vote = $this->getUserVote($user);

        if (!$vote) {
            return self::USER_NO_VOTE;
        }

        return $vote->getChoice();
    }

    /**
     * @param User $user
     *
     * @return null|Vote
     */
    private function getUserVote(User $user) {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('user', $user));

        return $this->getVotes()->matching($criteria)->first() ?: null;
    }
}

src/AppBundle/Resources/views/macros/comments.html.twig
{#
 # Options:
 #
 # - recurse (bool): true
 # - show_form (bool): false
 #}
{% macro comment(comment, options) %}
  {{- block('comment') -}}
{% endmacro %}

{% macro comment_form(submission, comment) %}
  {% if is_granted('ROLE_USER') %}
    {{ render(controller('RadditAppBundle:Comment:commentForm', {
      forumName: submission.forum.name,
      submissionId: submission.id,
      commentId: comment.id|default(null)
    })) }}
  {% else %}
    <div class="alert alert--notice">
      <p>{{ 'comments.not_logged_in'|trans({
        '%login_link%': '<a href="%s">%s</a>'|format(
          path('raddit_app_login'),
          'comments.not_logged_in_login_link_label'|trans
        ),
        '%register_link%': '<a href="%s">%s</a>'|format(
          path('raddit_app_registration'),
          'comments.not_logged_in_register_link_label'|trans
        ),
      })|raw }}</p>
    </div>
  {% endif %}
{% endmacro %}

{%- block comment -%}
  {%- from '@RadditApp/macros/votes.html.twig' import vote -%}
  <article class="comment comment-{{ level|default(0) ? 'level-'~level : 'top-level' }} {{ comment.softDeleted ? 'comment-soft-deleted' }}" id="comment_{{ comment.id }}">
    <div class="comment-row">
      <div class="comment-vote">
        {{ vote(comment, 'raddit_app_comment_vote') }}
      </div>

      <div class="comment-inner">
        <h1 class="comment-info">
          {{ 'comments.info'|trans({
            '%user%': block('comment_info_user'),
            '%timestamp%': block('comment_info_timestamp'),
          })|raw }}

          {% if comment.editedAt %}
            <span class="comment-info-edited-at {{ comment.moderated ? 'comment-info-moderated' }}">
              {{ (comment.moderated ? 'comments.moderator_info' : 'comments.edit_info')|trans({
                '%edited_at%': block('comment_info_edited_at')
              })|raw }}
            </span>
          {% endif %}
        </h1>

        <div class="comment-body">
          {{ comment.body|cached_markdown|raw }}
        </div>

        <nav class="comment-nav">
          <ul>{{ block('comment_nav') }}</ul>
        </nav>

        {% if options.show_form ?? false and is_granted('ROLE_USER') %}
          {% from _self import comment_form %}
          {{ comment_form(comment.submission, comment) }}
        {% endif %}
      </div>
    </div>

    {% if options.recurse ?? true and comment.children|length > 0 %}
      <div class="comment-replies">
        {%- for reply in comment.children -%}
          {%- with { comment: reply, level: level|default(0) + 1} only -%}
            {{- block('comment') -}}
          {%- endwith -%}
        {%- endfor -%}
      </div>
    {% endif %}
  </article>
{%- endblock -%}

{%- block comment_info_user -%}
  {%- from '@RadditApp/macros/user_macros.html.twig' import user_link -%}

  {%- if not comment.softDeleted -%}
    {{- user_link(comment.user, {
      class: 'comment-user',
      flag: comment.userFlag,
      submitter: comment.user is same as(comment.submission.user),
    }) -}}
  {%- else -%}
    {{- 'comments.author_deleted'|trans -}}
  {%- endif -%}
{%- endblock -%}

{%- block comment_info_timestamp -%}
  {%- set date = comment.timestamp|localizeddate('long', 'short') -%}
  <time datetime="{{ comment.timestamp|date('c') }}" title="{{ date }}" class="comment-timestamp relative-time">
    {{- 'comments.info_at_timestamp'|trans({'%timestamp%': date}) -}}
  </time>
{%- endblock -%}

{%- block comment_info_edited_at -%}
  {%- set date = comment.editedAt|localizeddate('long', 'short') -%}
  <time datetime="{{ comment.editedAt|date('c') }}" title="{{ date }}" class="relative-time-diff" data-compare-to="{{ comment.timestamp|date('c') }}">
    {{- 'comments.info_at_timestamp'|trans({'%timestamp%': date}) -}}
  </time>
{%- endblock -%}

{%- block comment_nav -%}
  {{- block('comment_nav_reply') -}}
  {{- block('comment_nav_permalink') -}}
  {{- block('comment_nav_parent') -}}
  {{- block('comment_nav_delete') -}}
  {{- block('comment_nav_edit') }}
  {{- block('comment_nav_ban') -}}
  {{- block('comment_nav_ip_ban') -}}
{%- endblock -%}

{%- block comment_nav_reply -%}
  <li class="comment-nav-reply" style="display: none">
    <a href="#" data-form-url="{{ path('raddit_app_comment_form', {
      forumName: comment.submission.forum.name,
      submissionId: comment.submission.id,
      commentId: comment.id
    }) }}">
      {{- 'comments.reply'|trans -}}
    </a>
  </li>
{%- endblock -%}

{%- block comment_nav_permalink -%}
  {%- spaceless -%}
    <li class="comment-nav-permalink">
      <a href="{{ path('raddit_app_comment', {
        forum_name: comment.submission.forum.name,
        submission_id: comment.submission.id,
        comment_id: comment.id
      }) }}">{{ 'comments.permalink'|trans }}</a>
    </li>
  {%- endspaceless -%}
{%- endblock -%}

{%- block comment_nav_parent -%}
  {%- spaceless -%}
    {%- if comment.parent -%}
      <li class="comment-nav-parent">
        <a href="{{ path('raddit_app_comment', {
          forum_name: comment.submission.forum.name,
          submission_id: comment.submission.id,
          comment_id: comment.parent.id
        }) }}">{{ 'comments.parent'|trans }}</a>
      </li>
    {%- endif -%}
  {%- endspaceless -%}
{%- endblock -%}

{# Forms are used here because we need to support JS-less browsing and because
 # GET requests should never mutate the state of the application. #}
{%- block comment_nav_delete -%}
  {%- if comment.children|length > 0 and is_granted('delete_thread', comment) -%}
    {%- set delete_thread_label = 'comments.delete_thread' -%}
    {{- block('comment_nav_delete_thread') -}}
    {{- block('comment_nav_delete_softdelete') -}}
  {%- elseif is_granted('delete', comment) -%}
    {%- set delete_thread_label = 'comments.delete' -%}
    {{- block('comment_nav_delete_thread') -}}
  {%- endif -%}
{%- endblock -%}

{%- block comment_nav_delete_softdelete -%}
  {%- spaceless -%}
    <li class="comment-nav-softdelete">
      <form action="{{ path('raddit_app_softdelete_comment', {id: comment.id}) }}" method="POST">
        <input type="hidden" name="token" value="{{ csrf_token('softdelete_comment') }}">
        <button type="submit">{{ 'comments.delete'|trans }}</button>
      </form>
    </li>
  {%- endspaceless -%}
{%- endblock -%}

{%- block comment_nav_delete_thread -%}
  {%- spaceless -%}
    <li class="comment-nav-delete-thread">
      <form action="{{ path('raddit_app_delete_comment', {id: comment.id}) }}" method="POST">
        <input type="hidden" name="token" value="{{ csrf_token('delete_comment') }}">
        <button type="submit">{{ delete_thread_label|trans }}</button>
      </form>
    </li>
  {%- endspaceless -%}
{%- endblock -%}

{%- block comment_nav_edit -%}
  {%- spaceless -%}
    {%- if is_granted('edit', comment) -%}
      <li class="comment-nav-edit">
        <a href="{{ path('raddit_app_edit_comment', {
          forum_name: comment.submission.forum.name,
          submission_id: comment.submission.id,
          comment_id: comment.id,
        }) }}">{{ 'comments.edit'|trans }}</a>
      </li>
    {%- endif -%}
  {%- endspaceless -%}
{%- endblock -%}

{%- block comment_nav_ban -%}
  {%- if is_granted('moderator', comment.submission.forum) -%}
    {%- spaceless -%}
      <li>
        <a href="{{ path('raddit_app_forum_ban', {forum_name: comment.submission.forum.name, username: comment.user.username}) }}">
          {{- 'action.ban'|trans -}}
        </a>
      </li>
    {%- endspaceless -%}
  {%- endif -%}
{%- endblock -%}

{%- block comment_nav_ip_ban -%}
  {%- if is_granted('ROLE_ADMIN') %}
    {%- spaceless -%}
      <li class="comment-nav-edit">
        <a href="{{ path('raddit_app_ban_ip_by_comment', {id: comment.id}) }}">
          {{- 'comments.admin_ban'|trans -}}
        </a>
      </li>
    {%- endspaceless -%}
  {%- endif -%}
{%- endblock -%}

src/AppBundle/Resources/views/macros/forum_list_macros.html.twig
{% macro forum_list_header() %}
  {% spaceless %}
    <nav class="forum-list-view-selector">
      <ul>
        <li class="{{ app.request.attributes.get('_route') == 'raddit_app_forum_list' ? 'active' }}">
          <a href="{{ path('raddit_app_forum_list') }}">{{ 'forum_list.list_view'|trans }}</a>
        </li>
        <li class="{{ app.request.attributes.get('_route') == 'raddit_app_forums_by_category' ? 'active' }}">
          <a href="{{ path('raddit_app_forums_by_category') }}">{{ 'forum_list.category_view'|trans }}</a>
        </li>
      </ul>
    </nav>
  {% endspaceless %}

  <h1>{{ 'forum_list.page_title'|trans }}</h1>

  {% if is_granted('create_forum') %}
    {% spaceless %}
      <nav class="horizontal-nav forum-list-bottom-nav">
        <ul>
          <li><a href="{{ path('raddit_app_create_forum') }}" class="button">{{ 'forum_list.create_forum'|trans }}</a></li>
        </ul>
      </nav>
    {% endspaceless %}
  {% endif %}
{% endmacro %}

src/AppBundle/Resources/views/macros/forum_macros.html.twig
{% macro subscribe_button(forum, subscribed, inline) %}
  {% set subscriber_count = forum.subscriptions|length %}
  {% from '@RadditApp/macros/icon.html.twig' import icon %}
  <button class="subscribe-button subscribe-button--{{ subscribed ? 'unsubscribe' : 'subscribe' }} {{ inline ? 'subscribe-button--inline' }}">
    <span class="subscribe-button__inner">
      <span class="subscribe-button__label">
        {{- (subscribed ? 'forum.unsubscribe' : 'forum.subscribe')|trans -}}
      </span>

      <span class="subscribe-button__subscriber-count" aria-label="{{ 'forum.subscriber_count'|transchoice(subscriber_count) }}">
        {{- subscriber_count|localizednumber -}}
      </span>
    </span>
  </button>
{% endmacro %}

src/AppBundle/Resources/views/macros/icon.html.twig
{%- macro icon(name, alt_text = '') -%}
  <span class="icon">
    {%- if alt_text|length > 0 -%}
      {#- Attempt to display an empty SVG. If this fails, the alt text will
          display. We assume that no support for SVG via <img> = no inline SVG
          support, although this assumption doesn't always hold true for older
          browsers (which we don't care about anyway). This hack is necessary to
          provide alternative text for Tor browser in high security mode, where
          SVG icons are disabled. -#}
      <img src="data:image/svg+xml,{{ '<svg xmlns="http://www.w3.org/2000/svg"/>'|url_encode }}" alt="{{ alt_text }}" class="icon__alt" aria-hidden="true">
    {%- endif -%}
    {{- source('@RadditApp/icons/%s.svg'|format(name)) -}}
  </span>
{%- endmacro -%}

src/AppBundle/Resources/views/macros/messages.html.twig
{% macro message_thread(message, options) %}
  {% set recursive = options.recursive ?? true %}
  {{ block('message_thread') }}
{% endmacro %}

{% macro message_reply(message) %}
  {{ block('message_reply') }}
{% endmacro %}

{% block message_thread %}
  <article class="message-thread" id="mt{{ message.id }}">
    <div class="message-thread-inner">
      {{ block('message_head') }}
      {{ block('message_body') }}
    </div>

    {% if recursive %}
      {% for message in message.replies %}
        {{ block('message_reply') }}
      {% endfor %}
    {% endif %}
  </article>
{% endblock %}

{% block message_reply %}
  <article class="message-reply" id="mr{{ message.id }}">
    {{ block('message_head') }}
    {{ block('message_body') }}
  </article>
{% endblock %}

{% block message_head %}
  <h1 class="message-head">
    <a href="{{ path('raddit_app_user', {username: message.sender.username}) }}" class="message-sender {{ message.sender == app.user ? 'message-self' }}">
      {{- message.sender.username -}}
    </a>

    {% with {date: message.timestamp|localizeddate()} %}
      <time datetime="{{ message.timestamp|date('c') }}" title="{{ date }}" class="relative-time">
        {{- date -}}
      </time>
    {% endwith %}
  </h1>
{% endblock %}

{% block message_body %}
  <div class="message-body">{{ message.body|cached_markdown|raw }}</div>
{% endblock %}

src/AppBundle/Resources/views/macros/submissions.html.twig
{%- macro submission(submission, options) -%}
  {%- set options = {
    show_body: false,
    show_forum_name: true,
  }|merge(options|default({})) -%}

  {{- block('submission') -}}
{%- endmacro -%}

{%- macro submission_sort(current) -%}
  {%- spaceless -%}
    {%- for type in ['hot', 'new', 'top', 'controversial'] -%}
      <li class="{{ type == current ? 'active' }}">
        <a href="{{ path(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')|default([])|merge({page: 1, sortBy: type})) }}">
          {{- ('submissions.sort_by_'~type)|trans -}}
        </a>
      </li>
    {%- endfor -%}
  {%- endspaceless -%}
{%- endmacro -%}

{%- block submission_info_submitter -%}
  {%- from '@RadditApp/macros/user_macros.html.twig' import user_link -%}
  {{ user_link(submission.user, {
    class: 'submission-submitter',
    flag: submission.userFlag,
  }) }}
{%- endblock -%}

{%- block submission_info_timestamp -%}
  {%- set date = submission.timestamp|localizeddate('long', 'short') -%}
  <time datetime="{{ submission.timestamp|date('c') }}" title="{{ date }}" class="submission-timestamp relative-time">
    {{- 'submissions.info_at_timestamp'|trans({'%timestamp%': date}) -}}
  </time>
{%- endblock -%}

{%- block submission_info_forum_name -%}
  <a href="{{ path('raddit_app_forum', {forum_name: submission.forum.name}) }}" class="submission-forum">
    {{- submission.forum.name -}}
  </a>
{%- endblock -%}

{%- block submission_info_edited_at -%}
  {%- set date = submission.editedAt|localizeddate('long', 'short') -%}
  <time datetime="{{ submission.editedAt|date('c') }}" title="{{ date }}" class="relative-time-diff" data-compare-to="{{ submission.timestamp|date('c') }}">
    {{- 'submissions.info_at_timestamp'|trans({'%timestamp%': date}) -}}
  </time>
{%- endblock -%}

{%- block submission -%}
  {%- from '@RadditApp/macros/votes.html.twig' import vote -%}
  <article class="submission {{ submission.url ? 'submission-has-url' }} {{ submission.body is not null ? 'submission-has-body' }} {{ not options.show_body ? 'submission-body-hidden' }} {{ submission.sticky ? 'submission-sticky' }}">
    <div class="submission-row">
      <div class="submission-vote">
        {{- vote(submission, 'raddit_app_submission_vote') -}}
      </div>

      {% if submission.image %}
        <div class="submission-image-container">
          <a href="{{ block('submission_url') }}" class="submission-image">
            <img src="{{ submission.image|imagine_filter('submission_thumbnail') }}" class="submission-thumbnail" alt="">
          </a>
        </div>
      {% endif %}

      <div class="submission-inner">
        <header class="submission-header">
          <h1 class="submission-title">
            <a href="{{ block('submission_url') }}" class="submission-link">
              {{- submission.title -}}
            </a>

            {% if submission.url is not empty and '://' in submission.url %}
              <small class="submission-host">
                {%- with {host: submission.url|split('://')[1]|split('/')[0]} -%}
                  {{- host[0:4] == 'www.' ? host[4:] : host -}}
                {%- endwith -%}
              </small>
            {% endif %}
          </h1>

          <p class="submission-info">
            {%- if options.show_forum_name -%}
              {{ 'submissions.info_with_forum_name'|trans({
                '%submitter%': block('submission_info_submitter'),
                '%timestamp%': block('submission_info_timestamp'),
                '%forum%': block('submission_info_forum_name'),
              })|raw }}
            {%- else -%}
              {{ 'submissions.info_without_forum_name'|trans({
                '%submitter%': block('submission_info_submitter'),
                '%timestamp%': block('submission_info_timestamp'),
              })|raw }}
            {%- endif -%}

            {% if submission.editedAt %}
              <span class="submission-info-edited-at {{ submission.moderated ? 'submission-info-moderated' }}">
                {{ (submission.moderated ? 'submissions.moderator_info' : 'submissions.edit_info')|trans({
                  '%edited_at%': block('submission_info_edited_at')
                })|raw }}
              </span>
            {% endif %}

            {% if app.environment == 'dev' and app.request.query.has('showrank') %}
              {{ submission.ranking - submission.timestamp.timestamp  }}
            {% endif %}
          </p>
        </header>

        {%- if options.show_body -%}
          {% if submission.url %}
            <div class="submission-media">{{ block('submission_media') }}</div>
          {% endif %}

          {% if submission.body is not null %}
            <div class="submission-body">{{ submission.body|cached_markdown|raw }}</div>
          {% endif %}
        {%- endif -%}

        {%- spaceless -%}
          <nav class="submission-nav">
            <ul>
              <li>
                <a href="{{ path('raddit_app_comments', {forum_name: submission.forum.name, submission_id: submission.id, slug: submission.title|slugify}) }}">
                  {{- 'submissions.comments'|transchoice(submission.comments|length) -}}
                </a>
              </li>
              {%- if is_granted('edit', submission) -%}
                <li>
                  <a href="{{ path('raddit_app_edit_submission', {forum_name: submission.forum.name, submission_id: submission.id}) }}">
                    {{- 'submissions.edit'|trans -}}
                  </a>
                </li>
              {%- endif -%}
              {%- if is_granted('moderator', submission.forum) -%}
                <li>
                  <a href="{{ path('raddit_app_forum_ban', {forum_name: submission.forum.name, username: submission.user.username}) }}">
                    {{- 'action.ban'|trans -}}
                  </a>
                </li>
              {%- endif -%}
              {%- if is_granted('ROLE_ADMIN') -%}
                <li>
                  <a href="{{ path('raddit_app_ban_ip_by_submission', {id: submission.id}) }}">{{ 'submissions.ip_ban'|trans }}</a>
                </li>
              {%- endif -%}
            </ul>
          </nav>
        {%- endspaceless -%}
      </div>
    </div>
  </article>
{% endblock %}

{%- block submission_url -%}
  {%- if submission.url -%}
    {{- submission.url -}}
  {%- else -%}
    {{- path('raddit_app_comments', {forum_name: submission.forum.name, submission_id: submission.id, slug: submission.title|slugify}) -}}
  {%- endif -%}
{%- endblock -%}

{%- block submission_media -%}
  {# TODO #}
{%- endblock -%}

src/AppBundle/Resources/views/macros/user_macros.html.twig
{##
 # - submitter (bool): If comment author is the submission author
 # - flag (int): one of Raddit\AppBundle\Entity\UserFlags constants
 # - class (string): Additional classes
 #}
{%- macro user_link(user, options) -%}
  {%- from _self import _class_by_flag -%}
  <a href="{{ path('raddit_app_user', {username: user.username}) }}"
     class="{{ (options.submitter ?? false) ? 'submitter' }} {{ _class_by_flag(options.flag ?? 0) }} {{ options.class ?? '' }}">
    {{- user.username -}}
  </a>
  {%- if options.flag ?? 0 == 0 -%}
  {% elseif options.flag == constant('Raddit\\AppBundle\\Entity\\UserFlags::FLAG_ADMIN') %}
    <small class="user-flag user-flag-admin">{{ 'user_flag.admin'|trans }}</small>
  {% elseif options.flag == constant('Raddit\\AppBundle\\Entity\\UserFlags::FLAG_MODERATOR') %}
    <small class="user-flag user-flag-moderator">{{ 'user_flag.moderator'|trans }}</small>
  {%- endif -%}
{%- endmacro -%}

{%- macro _class_by_flag(flag) -%}
  {%- if flag == 0 -%}
    {#- early exit -#}
  {%- elseif flag == constant('Raddit\\AppBundle\\Entity\\UserFlags::FLAG_ADMIN') -%}
    flag-admin
  {%- elseif flag == constant('Raddit\\AppBundle\\Entity\\UserFlags::FLAG_MODERATOR') -%}
    flag-moderator
  {%- endif -%}
{%- endmacro -%}

src/AppBundle/Resources/views/macros/votes.html.twig
{%- macro vote(entity, route) -%}
  {{- block('vote') -}}
{%- endmacro -%}

{%- block vote -%}
  {%- from '@RadditApp/macros/icon.html.twig' import icon -%}

  {%- set user_choice = is_granted('ROLE_USER') ? entity.userChoice(app.user) : null -%}
  {%- spaceless -%}
    <form action="{{ path(route, {id: entity.id}) }}"
          method="post"
          class="vote {{ block('vote_class') }}"
          data-ajax-action="{{ path(route, {id: entity.id, _format: 'json'}) }}"
          data-score="{{ entity.netScore }}">

      {# csrf_token starts a session #}
      {% if is_granted('ROLE_USER') %}
        <input type="hidden" name="token" value="{{ csrf_token('vote') }}">
      {% endif %}

      <button type="submit" name="choice" value="{{ block('vote_choice_up') }}"
              class="vote-button vote-up" title="{{ block('vote_up_label') }}">
        <span class="inner" aria-hidden="true">{{ icon('up', 'up') }}</span>
      </button>

      <span class="vote-score">{{ entity.netScore }}</span>

      <button type="submit" name="choice" value="{{ block('vote_choice_down') }}"
              class="vote-button vote-down" title="{{ block('vote_down_label') }}">
        <span class="inner" aria-hidden="true">{{ icon('down', 'down') }}</span>
      </button>
    </form>
  {%- endspaceless -%}
{%- endblock -%}

{%- block vote_class -%}
  {%- if user_choice == constant('Raddit\\AppBundle\\Entity\\Votable::USER_UPVOTED') -%}
    vote-user-upvoted
  {%- elseif user_choice == constant('Raddit\\AppBundle\\Entity\\Votable::USER_DOWNVOTED') -%}
    vote-user-downvoted
  {%- endif -%}
{%- endblock -%}

{%- block vote_choice_up -%}
  {{- user_choice == constant('Raddit\\AppBundle\\Entity\\Votable::USER_UPVOTED')
    ? constant('Raddit\\AppBundle\\Entity\\Votable::VOTE_RETRACT')
    : constant('Raddit\\AppBundle\\Entity\\Votable::VOTE_UP')
  -}}
{%- endblock -%}

{%- block vote_choice_down -%}
  {{- user_choice == constant('Raddit\\AppBundle\\Entity\\Votable::USER_DOWNVOTED')
    ? constant('Raddit\\AppBundle\\Entity\\Votable::VOTE_RETRACT')
    : constant('Raddit\\AppBundle\\Entity\\Votable::VOTE_DOWN')
  -}}
{%- endblock -%}

{%- block vote_up_label -%}
  {{- (user_choice == constant('Raddit\\AppBundle\\Entity\\Votable::USER_UPVOTED')
    ? 'action.retract_upvote'
    : 'action.upvote'
  )|trans -}}
{%- endblock -%}

{%- block vote_down_label -%}
  {{- (user_choice == constant('Raddit\\AppBundle\\Entity\\Votable::USER_DOWNVOTED')
    ? 'action.retract_downvote'
    : 'action.downvote'
  )|trans -}}
{%- endblock -%}