src/AppBundle/Entity/Message.php
<?php

namespace Raddit\AppBundle\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Selectable;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\MappedSuperclass()
 */
abstract class Message {
    /**
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue()
     * @ORM\Id()
     *
     * @var int|null
     */
    private $id;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $sender;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $body;

    /**
     * @ORM\Column(type="datetimetz")
     *
     * @var \DateTime
     */
    private $timestamp;

    /**
     * @ORM\Column(type="inet")
     *
     * @var string|null
     */
    private $ip;

    /**
     * Message constructor.
     *
     * @param User        $sender
     * @param string      $body
     * @param string|null $ip
     */
    public function __construct(User $sender, string $body, $ip) {
        if ($ip !== null && !filter_var($ip, FILTER_VALIDATE_IP)) {
            throw new \InvalidArgumentException('$ip must be valid IP address or NULL');
        }

        $this->sender = $sender;
        $this->body = $body;
        $this->ip = $ip;
        $this->timestamp = new \DateTime('@'.time());
    }

    /**
     * @return int|null
     */
    public function getId() {
        return $this->id;
    }

    public function getSender(): User {
        return $this->sender;
    }

    public function getBody(): string {
        return $this->body;
    }

    public function getTimestamp(): \DateTime {
        return $this->timestamp;
    }

    /**
     * @return string|null
     */
    public function getIp() {
        return $this->ip;
    }

    /**
     * @return Notification[]|Collection|Selectable
     */
    abstract public function getNotifications();
}

src/AppBundle/Resources/views/includes/meta_pagination.html.twig
{% with {attr: app.request.attributes} %}
  {% if pager.hasPreviousPage %}
    <link rel="prev" href="{{ path(attr.get('_route'), attr.get('_route_params')|default({})|merge({page: pager.previousPage})) }}">
  {% endif %}

  {% if pager.hasNextPage %}
    <link rel="next" href="{{ path(attr.get('_route'), attr.get('_route_params')|default({})|merge({page: pager.nextPage})) }}">
  {% endif %}
{% endwith %}

src/AppBundle/Resources/views/includes/pagination.html.twig
{% with {attr: app.request.attributes} %}
  <nav class="pagination">
    <ul>
      {% if pager.hasPreviousPage %}
        <li class="previous">
          <a href="{{ path(attr.get('_route'), attr.get('_route_params')|default({})|merge({page: pager.previousPage})) }}">
            {{ 'nav.previous'|trans }}
          </a>
        </li>
      {% endif %}
      {% if pager.hasNextPage %}
        <li class="next">
          <a href="{{ path(attr.get('_route'), attr.get('_route_params')|default({})|merge({page: pager.nextPage})) }}">
            {{ 'nav.next'|trans }}
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endwith %}

src/AppBundle/Resources/views/includes/site_nav.html.twig
{% from '@RadditApp/macros/icon.html.twig' import icon %}
{% spaceless %}
  {%- set notification_count = is_granted('ROLE_USER') ? app.user.notifications|length : 0 -%}

  <nav class="site-nav">
    <div class="site-nav__header">
      <a href="{{ path('raddit_app_front') }}" class="site-nav__logo">{{ raddit_app_site_name() }}</a>
      {# todo: accessibility #}
      <a href="#" class="site-nav__mobile-toggle {{ notification_count > 0 ? 'site-nav__mobile-toggle--has-notifications' }}" onclick="$(this).parents('.site-nav').find('.site-nav__inner').toggleClass('site-nav__inner--mobile-visible'); return false">{{ icon('menu') }}</a>
    </div>

    <div class="site-nav__inner">
      {# left portion of site nav #}
      <ul class="site-nav__menu">
        <li class="site-nav__item">
          <a href="{{ path('raddit_app_forum_list') }}" class="site-nav__link">{{ 'nav.forums'|trans }}</a>
        </li>

        <li class="site-nav__item">
          <a href="{{ path('raddit_app_wiki') }}" class="site-nav__link">{{ 'nav.wiki'|trans }}</a>
        </li>
      </ul>

      {# right portion of site nav #}
      <ul class="site-nav__menu right-nav">
        {% if not is_granted('ROLE_USER') %}
          <li class="site-nav__item">
            <a href="{{ path('raddit_app_login') }}" class="site-nav__link">{{ 'nav.log_in'|trans }}</a>
          </li>

          <li class="site-nav__item">
            <a href="{{ path('raddit_app_registration') }}" class="site-nav__link">{{ 'nav.register'|trans }}</a>
          </li>
        {% else %}
          {# notifications #}
          {% if notification_count > 0 %}
            <li class="site-nav__item site-nav__item--has-notifications">
              <a href="{{ path('raddit_app_inbox') }}" class="site-nav__link">
                {{- 'nav.inbox_count'|trans({'%count%': '<strong>%d</strong>'|format(notification_count)})|raw -}}
              </a>
            </li>
          {% endif %}

          {# submit button #}
          <li class="site-nav__item">
            <a href="{{ path('raddit_app_submit', {forum_name: forum is defined and forum ? forum.name : null}) }}" class="site-nav__link">
              {{- 'nav.submit'|trans -}}
            </a>
          </li>

          {# user menu #}
          <li class="site-nav__item dropdown-container">
            <a href="#" class="site-nav__link dropdown-toggle"><strong>{{ app.user.username }}</strong></a>
            <ul class="dropdown-menu">
              <li><a href="{{ path('raddit_app_user', {username: app.user.username}) }}">{{ icon('user') }} {{ 'nav.profile'|trans }}</a></li>
              <li><a href="{{ path('raddit_app_message_list') }}">{{ icon('mail') }} {{ 'nav.messages'|trans }}</a></li>
              <li><a href="{{ path('raddit_app_edit_user', {username: app.user.username}) }}">{{ icon('lock') }} {{ 'nav.my_account'|trans }}</a></li>
              <li><a href="{{ path('raddit_app_user_settings', {username: app.user.username}) }}">{{ icon('settings') }} {{ 'nav.user_settings'|trans }}</a></li>
              <li><a href="{{ logout_path() }}">{{ icon('logout') }} {{ 'nav.log_out'|trans }}</a></li>
            </ul>
          </li>

        {% endif %}
      </ul>
    </div>
  </nav>
{% endspaceless %}

src/AppBundle/Resources/views/includes/stylesheets.html.twig
{% if theme is null or theme.appendToDefaultStyle %}
  {% if not night_mode %}
    <link rel="stylesheet" href="{{ preload(asset('build/red.css')) }}">
  {% else %}
    <link rel="stylesheet" href="{{ preload(asset('build/night.css')) }}">
  {% endif %}
{% endif %}

{% if theme is not null %}
  <link rel="stylesheet" href="{{ path('raddit_app_stylesheet', {
    id: theme.id,
    field: 'common',
    unixTime: theme.lastModified|date('U'),
  }) }}">
  <link rel="stylesheet" href="{{ path('raddit_app_stylesheet', {
    id: theme.id,
    field: night_mode ? 'night' : 'day',
    unixTime: theme.lastModified|date('U'),
  }) }}">
{% endif %}